<?php
$page = $item['title'];

include __DIR__ . '/header.phtml';
?>
    <section>
      <div class="container">
        <div class="entry-list single">
          <article>
            <h1><?php echo $item['title']; ?></h1>
            <time datetime="<?php $item['date']; ?>"><?php echo date('F d, Y', strtotime($item['date'])); ?></time>
            <div class="entry">
              <p><?php echo $item['body']; ?></p>
              <?php
              if (!empty($item['tags'])) {
                  $tags = explode(',', $item['tags']);
                  echo "<ul>";
                  foreach ($tags as $tag) {
                      echo "<li><a href='/../tags/" . trim($tag) . "'>#" . trim($tag) . "</a></li>";
                  }
                  echo "</ul>";
              }
              ?>
              <p><a class="link" href="/edit/<?php echo $item['slug'];  ?>">Edit Entry</a></p>
              <p><a class="link" href="/delete/<?php echo $item['slug']; ?>">Delete Entry</a></p>
            </div>
          </article>
        </div>
      </div>
    </section>
    <section class="entry-comments">
      <div class="container">
      <h2>Comments</h2>
        <div class="comment">
          <?php
          foreach ($comments as $comment) {
              echo "<strong>" . $comment['name'] . "</strong>";
              echo "<p>" . $comment['body'] . "</p>";
          }
          ?>
        </div>
        <div class="new-comment">
          <form method="post">
            <label for="name">Name<span style="color:red">*</span></label>
            <input type="text" name="name" required><br>
            <label for="comment">Comment<span style="color:red">*</span></label>
            <textarea rows="5" name="comment_body" required></textarea>
            <input type="submit" value="Post Comment" class="button">
          </form>
        </div>
      </div>
    </section>
<?php include __DIR__ . '/footer.phtml'; ?>
