<?php
$page = "Edit Entry";

include __DIR__ . '/header.phtml';
?>
    <section>
      <div class="container">
        <div class="edit-entry">
          <h2>Edit Entry</h2>
          <form method="post">
            <label for="title">Title</label>
            <input type="text" name="title" value="<?php echo $item['title']; ?>"><br>
            <label for="date">Date</label>
            <input type="date" name="date" value="<?php echo $item['date']; ?>"><br>
            <label for="entry">Entry</label>
            <textarea rows="5" name="entry"><?php echo $item['body']; ?></textarea>
            <label for="tags">Tags (separate with commas)</label>
            <textarea rows="2" name="tags"><?php echo $item['tags']; ?></textarea>
            <input type="submit" value="Save Entry" class="button">
            <a href="/delete/<?php echo $item['slug']; ?>" class="button button-secondary">Delete Entry</a>
            <a href="index.pthml" class="button button-secondary">Cancel</a>
          </form>
        </div>
      </div>
    </section>
<?php include __DIR__ . '/footer.phtml'; ?>
