<?php
$page = 'Home';

include __DIR__ . '/header.phtml';
?>
    <section>
      <div class="container">
        <div class="entry-list">
          <?php
          foreach ($post->getPosts() as $item) {
              echo "<article>";
              echo "<h2><a href='entries/" . $item['slug'] . "'>" . $item['title'] . "</a></h2>";
              echo "<time datetime='" . $item['date'] . "'>" . date("F d, Y", strtotime($item['date'])) . "</time><br>";
              if (!empty($item['tags'])) {
                  $tags = explode(',', $item['tags']);
                  foreach ($tags as $tag) {
                      echo "<a href='tags/" . trim($tag) . "'>#" . trim($tag) . "</a> ";
                  }
              }
              echo "</article>";
          }
          ?>
        </div>
      </div>
    </section>
<?php include __DIR__ . '/footer.phtml'; ?>
