<?php
$page = $tag;

include __DIR__ . '/header.phtml';
?>
    <section>
      <div class="container">
        <div class="entry-list">
          <h1><?php echo "#" . trim($tag); ?></h1>
          <?php
          foreach ($items as $item) {
              echo "<article>";
              echo "<h2><a href='/../entries/" . $item['slug'] . "'>" . $item['title'] . "</a></h2>";
              echo "<time datetime='" . $item['date'] . "'>" . date("F d, Y", strtotime($item['date'])) . "</time><br>";
              $tags = explode(',', $item['tags']);
              foreach ($tags as $tag) {
                  echo "<a href='" . trim($tag) . "'>#" . trim($tag) . "</a> ";
              }
              echo "</article>";
          }
          ?>
        </div>
      </div>
    </section>
<?php include __DIR__ . '/footer.phtml'; ?>
